[tool.poetry]
name = "dataclass-validate"
version = "0.1.0"
description = ""
authors = ["MattG-bci"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
